---
- name: Ensure nginx is installed.
  pkgng:
    name: "{{ nginx_package_name }}"
    state: present

- name: Create logs directory.
  file:
    path: /var/log/nginx
    mode: 0750
    owner: "{{ __nginx_user }}"
    group: "{{ root_group }}"
    state: directory
